[firebase_credentials]
type = "service_account"
project_id = "performancereview-eb8c7"
private_key_id = "ab8c869359c5df1972ef432972d24d28a3b461fa"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDIbs2bJ5KmskGn
cvH4SJbEYvvnVBfhfaf5KmOUxVAJYFy3EshxP5ztrT4wWNI4qelIsiFgeEPP4Udl
HgP8W9XF26YeN4/zzsAZfhb9v4vsWJxQjW6uk9oqZucN/7WRuhStf/qbiFEW4YWj
rt/MTIGapLdeLIn1p3tl0A+NJ9PoEVThc7nr+YLj7BKHX2bpnvY0Mp0guQy1utu0
FOqGLZ7bgVTnBuqJQLafXPv3SBCp8PTVk8tGoat3vrEHKprF20nuLAaPM828dki6
/7VkmNvpoerxE7FQ9youE0N50XKDnm2UOGNx1a4H922/8MZ/yIC0ViY75JTDCI1z
PjHBv7ZFAgMBAAECggEAAQFwpdC47iiuXhS6NZGDRInhES0LOFztDSz4WpG3d5Gk
noK6Q9QhGFpAyMZZC0TWTibzlDgUp2t42qWsyhPvAxhGUHoyltE3l1tJJfHxXkv8
yOw2mve6o73bQ42ACl1ahz0wStGDY5MVZR5DR9NhCsGa2GMIQQkGKzCFM7ie2hPM
s3fIt3AaP7G2NbnmSoHcbhWRVTy5IRyNYJxCWuJIxUfg2WYgPnAZJYdf5dSXa9l7
6Dv5vaW8c1QVYb121IC8DJQ0IlLp1BnhTN+C738wGSQHf1tmvYVkfEuP+pPG7MgI
RAm+0pOCCJi8Vky8G04jgYjngaNKDKiHpQexW1LLOQKBgQD4siBpeI7hSldJWtT+
KXRvcMiAqGmKJrOIQpL1cKzQcdEresO2jxghSk0AoXrx0SVy+oPgz09FUCuMV6pb
5q3aHPyNYr2+joCuWdl3kpzXgSvYrjWClfv0z7IfGrzycIQ7T26VpaR9txdEWIYR
gR5Yq9y4/FzBvTzZTVqZc+R/jQKBgQDOUc0DfLSQmqm2ckCdgUidQQxVozrW8H3K
dfSwyN0CSpyiw7nVZguvbnqBbGM14suRIIJeemBMOwMT5wPAuHWOClDZmf33WDpZ
DoXudCNWe9oFMTVvHKnllwVBLDx6I1r8owKQmYy5vUK5zBrp56zVaSYuRQXRA2X4
j9IJNQUnmQKBgE4N0gBoVye8ZmLegET5C9NCKZu/v8gdV3Gnu2oPIB4X6tdjo3Nz
u9YO9NYC2Ix24PMSTzvKtQ2DGPfmN9C6OMxhFp7lY7ogDaErEAboXBODNhi+rIq8
uiRe33/Fq5HH4KigyIttPpA6W7IWupVZ2gVog1EH27DuzN9C2PGanxetAoGAaHYm
VSOo0KZeU0/Zw2WX/HbY5es1eWpeZkn+0BuDOwvH7ukmiBOYywQm5qyYNspTw3Ew
UOGpLC+cyVDoJ4W9j2NNuD8txTRYpoqh6S/ITJt8sbBOm6lppCMot+zL2hNYmB14
yPnVtJ1M0YG0BsYUTiFlAXxVC5Sq5oT7FUpRB9ECgYBm7KBhixJQiGxgEtjMXxfI
aEPYZQBZGwxeCGfZ7tD6v4cOAwmSAvbuSjBcX6sc5HvwUmOanQU5rXz8ProFYEZ1
v11OUgI7z44uV3JU937NiLq37IIUH4/fVhP1KBQMVkkSRZzBs2DorQBPFDmLdTW8
RZwHFaUubizRomL/haucPw==
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@performancereview-eb8c7.iam.gserviceaccount.com"
client_id = "114292735939873430867"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40performancereview-eb8c7.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
